name: Update Radio Data

on:
  schedule:
    - cron: "*/30 * * * *"
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update radio data
        run: node qtfm.js

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data.json
          git diff --staged --quiet || git commit -m "action: `date`"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}